// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsWebAPI.DbContexts;

namespace ProductsWebAPI.Migrations
{
    [DbContext(typeof(ProductLibraryContext))]
    partial class ProductLibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductsWebAPI.Entities.Category", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = new Guid("5b1c2b4d-48c7-402a-80c3-cc796ad49c6b"),
                            Name = "Electronics"
                        },
                        new
                        {
                            ID = new Guid("40ff5488-fdab-45b5-bc3a-14302d59869a"),
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("ProductsWebAPI.Entities.Product", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CateogryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            CateogryID = new Guid("5b1c2b4d-48c7-402a-80c3-cc796ad49c6b"),
                            ImgURL = "",
                            Name = "Battery",
                            Price = 90m,
                            Quantity = 120
                        },
                        new
                        {
                            ID = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            CateogryID = new Guid("5b1c2b4d-48c7-402a-80c3-cc796ad49c6b"),
                            ImgURL = "",
                            Name = "Screen",
                            Price = 150m,
                            Quantity = 80
                        },
                        new
                        {
                            ID = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            CateogryID = new Guid("40ff5488-fdab-45b5-bc3a-14302d59869a"),
                            ImgURL = "",
                            Name = "Headphones",
                            Price = 60m,
                            Quantity = 200
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
